repos:
  - repo: local
    hooks:
      - id: check
        name: Run all checks (just check)
        entry: just check
        language: system
        pass_filenames: false
        always_run: true
        
      - id: format
        name: Format code (just fix)  
        entry: just fix
        language: system
        types: [python]
        pass_filenames: false